AllCops:
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false
